name: 'Inject Amazon SSM wildcard to task definition Action for GitHub Actions'
description: 'Inserts a Wildcard AWS SSM into a container definition in an Amazon ECS task definition JSON file, creating a new file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  secretsWildcard:
    description: 'The Wildcard of the AWS SSM Parameter to insert into the ECS task definition'
    required: true
  aws_region:
    description: 'The Region of AWS'
    required: false
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'